#!/bin/sh
# Start/stop the SLA-NG manager daemon.
#
### BEGIN INIT INFO
# Provides:          sla-ng
# Required-Start:    $syslog  
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      1 6
# Short-Description: SLA-NG hardware ping management daemon 
### END INIT INFO

PATH="/sbin:/usr/sbin:/bin:/usr/bin"
NAME="sla-ng-manager"
DESC="SLA-NG Manager Daemon"
DAEMON="/usr/bin/$NAME"

. /lib/lsb/init-functions

killhard()
{
	pkill -f $NAME
	sleep 3
	pkill -9 -f $NAME
	pkill -9 -f probed
}

starthard()
{
	killhard
	$DAEMON
}

case "$1" in
start)
	log_daemon_msg "Starting $DESC" "$NAME"
	starthard
	log_end_msg 0
	;;
restart)
	log_daemon_msg "Restarting $DESC" "$NAME"
	starthard
	log_end_msg 0
	;;
stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	killhard
	log_end_msg 0
	;;
esac
