#!/bin/sh
# Start/stop the SLA-NG manager daemon.
#
### BEGIN INIT INFO
# Provides:          sla-ng
# Required-Start:    $syslog  
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      1 6
# Short-Description: SLA-NG hardware ping management daemon 
### END INIT INFO

PATH="/sbin:/usr/sbin:/bin:/usr/bin"
NAME="sla-ng-manager"
DESC="SLA-NG Manager Daemon"
DAEMON="/usr/bin/$NAME"

killhard()
{
	pkill -f $NAME
	sleep 3
	pkill -9 -f $NAME
	pkill -9 -f probed 
}

starthard()
{
	killhard
	$DAEMON
}

case "$1" in
start)
	echo "Starting $DESC" "$NAME"
	starthard
	;;
restart)
	echo "Restarting $DESC" "$NAME"
	starthard
	;;
stop)
	echo "Stopping $DESC" "$NAME"
	killhard
	;;
esac
